spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    username: item-service
    password: item-service
    url: jdbc:postgresql://postgres-item:5432/item

  rabbitmq:
    template:
      exchange-create: item.create
      exchange-update: item.update
      exchange-delete: item.delete
      exchange-inappropriate: item.inappropriate
      exchange-counterfeit: item.counterfeit
    host: rabbitmq-server
  sql:
    init:
      mode: always
      platform: postgres
server:
  port: 8088

jwt:
  secret: G+KbPeShVmYq3t6w9z$C&F)J@McQfTjW